"""Generates the S0 deterministic single-intersection scenario.

Routes are derived from the generated network rather than hand-written, because
netgenerate owns the edge identifiers. Re-running this script reproduces the committed
files byte for byte, on any machine.
"""

from __future__ import annotations

import math
import re
import subprocess
import sys
from pathlib import Path

# GOTCHA: importing sumo is what sets SUMO_HOME.
import sumo
import sumolib

REPO_ROOT = Path(__file__).resolve().parents[1]
SCENARIO_ROOT = REPO_ROOT / "scenarios" / "s0_single_intersection" / "v1"

GRID_LENGTH_M = 200.0  # Approach length; long enough to hold a queue without spilling out.
ATTACH_LENGTH_M = 200.0  # Stub length on each of the four approaches.
LANES_PER_DIRECTION = 2  # Minimum that permits a separate turning movement later.

# One vehicle every 6 s per approach = 600 veh/h/approach, comfortably undersaturated for
# a two-lane approach (regime A). S0 exists to be predictable.
HEADWAY_S = 6.0
# Departures stop two minutes before the scenario horizon of 600 s so the network drains
# on its own; S0 should exercise the drain path, not the horizon cut-off.
DEPART_END_S = 480.0

# SUMO's own default passenger-car vType (`sumo/src/microsim/MSVehicleType`
# / the vType.xsd defaults) — S0's fleet is intentionally the SUMO default, not a tuned one.
CAR_ACCEL_MPS2 = 2.6
CAR_DECEL_MPS2 = 4.5
CAR_LENGTH_M = 5.0
CAR_MAX_SPEED_MPS = 13.9  # 50 km/h, SUMO's default vType speed limit.


def build_network(output: Path) -> None:
    binary = Path(sumo.SUMO_HOME) / "bin" / "netgenerate"
    # netgenerate records the output path it was given inside the file, so it is invoked
    # from the scenario directory with a relative name; an absolute path would embed the
    # generating machine's filesystem in a committed, publicly published artifact.
    subprocess.run(
        [
            str(binary),
            "--grid",
            "--grid.number=1",
            f"--grid.length={GRID_LENGTH_M}",
            f"--grid.attach-length={ATTACH_LENGTH_M}",
            f"--default.lanenumber={LANES_PER_DIRECTION}",
            "--tls.guess=true",
            "--tls.default-type=static",
            "--no-turnarounds=true",
            "--output-file",
            output.name,
        ],
        cwd=output.parent,
        check=True,
    )
    _strip_generation_timestamp(output)


def _strip_generation_timestamp(network: Path) -> None:
    """Remove the wall-clock stamp netgenerate writes into its header comment.

    A scenario's identity is the sha256 of its files, so the bytes must depend only on the
    generator's inputs. The option list in the header is kept: it is real provenance.
    """
    network.write_text(re.sub(r"generated on [^ ]+ by", "generated by", network.read_text()))


# A straight-through movement must align with its approach to within 30 degrees. Anything
# looser starts labelling turns as through movements on an irregular junction.
MIN_STRAIGHT_ALIGNMENT = math.cos(math.radians(30.0))
# The winner must beat the runner-up by this much in cosine terms, or the pairing is a coin
# toss. 0.05 separates the 5-degree noise of a real approach from a genuine fork.
MIN_ALIGNMENT_MARGIN = 0.05


def _unit_direction(edge: sumolib.net.edge.Edge) -> tuple[float, float]:
    shape = edge.getShape()
    (start_x, start_y), (end_x, end_y) = shape[0], shape[-1]
    dx, dy = end_x - start_x, end_y - start_y
    norm = math.hypot(dx, dy)
    if norm == 0.0:
        raise ValueError(f"edge {edge.getID()} has zero-length geometry")
    return dx / norm, dy / norm


def _alignment(heading: tuple[float, float], edge: sumolib.net.edge.Edge) -> float:
    other = _unit_direction(edge)
    return heading[0] * other[0] + heading[1] * other[1]


def approach_pairs(
    incoming: list[sumolib.net.edge.Edge], outgoing: list[sumolib.net.edge.Edge]
) -> list[tuple[str, str]]:
    """Each incoming edge paired with its straight-through outgoing edge.

    Raises rather than guessing. A silently mislabelled through movement produces demand
    that looks correct and measures the wrong thing.
    """
    pairs: list[tuple[str, str]] = []
    for in_edge in sorted(incoming, key=lambda edge: edge.getID()):
        heading = _unit_direction(in_edge)
        scored = sorted(((_alignment(heading, out), out.getID()) for out in outgoing), reverse=True)
        best_score, best_id = scored[0]
        if best_score < MIN_STRAIGHT_ALIGNMENT:
            raise ValueError(
                f"edge {in_edge.getID()} has no straight-through outgoing edge: "
                f"best alignment {best_score:.3f} < {MIN_STRAIGHT_ALIGNMENT:.3f}"
            )
        if len(scored) > 1 and best_score - scored[1][0] < MIN_ALIGNMENT_MARGIN:
            raise ValueError(
                f"edge {in_edge.getID()} has an ambiguous straight-through pairing: "
                f"{best_id} at {best_score:.3f} versus {scored[1][1]} at {scored[1][0]:.3f}"
            )
        pairs.append((in_edge.getID(), best_id))
    return pairs


def _junction_pairs(net: sumolib.net.Net) -> list[tuple[str, str]]:
    junction = next(node for node in net.getNodes() if node.getType() == "traffic_light")
    return approach_pairs(list(junction.getIncoming()), list(junction.getOutgoing()))


def build_demand(network: Path, output: Path, *, depart_end_s: float = DEPART_END_S) -> None:
    net = sumolib.net.readNet(str(network))
    pairs = _junction_pairs(net)
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<routes>",
        f'    <vType id="car" accel="{CAR_ACCEL_MPS2}" decel="{CAR_DECEL_MPS2}" sigma="0.0" '
        f'length="{CAR_LENGTH_M}" maxSpeed="{CAR_MAX_SPEED_MPS}"/>',
    ]
    for index, (source, target) in enumerate(pairs):
        lines.append(f'    <route id="r{index}" edges="{source} {target}"/>')
    for index, _ in enumerate(pairs):
        lines.append(
            f'    <flow id="f{index}" route="r{index}" type="car" '
            f'begin="0.00" end="{depart_end_s:.2f}" period="{HEADWAY_S:.2f}" departLane="free"/>'
        )
    lines.append("</routes>")
    output.write_text("\n".join(lines) + "\n")


TURNING_SCENARIO_ROOT = REPO_ROOT / "scenarios" / "s0_turning" / "v1"

# Departure period in seconds per (approach, outgoing) movement. Deliberately asymmetric:
# no two approaches share a volume and no two movements within an approach share a share,
# so a movement-mapping error cannot hide behind symmetry. Measured behaviour of this mix
# is recorded in the M1a spec section 10.3.
TURNING_PERIODS_S: dict[str, dict[str, float]] = {
    "top0A0": {"A0left0": 48.0, "A0bottom0": 8.0, "A0right0": 24.0},
    "right0A0": {"A0top0": 16.0, "A0left0": 12.0, "A0bottom0": 40.0},
    "bottom0A0": {"A0right0": 32.0, "A0top0": 15.0, "A0left0": 20.0},
    "left0A0": {"A0bottom0": 12.0, "A0right0": 20.0, "A0top0": 60.0},
}


def build_turning_demand(
    output: Path,
    *,
    periods_s: dict[str, dict[str, float]] = TURNING_PERIODS_S,
    depart_end_s: float = DEPART_END_S,
) -> None:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<routes>",
        f'    <vType id="car" accel="{CAR_ACCEL_MPS2}" decel="{CAR_DECEL_MPS2}" sigma="0.0" '
        f'length="{CAR_LENGTH_M}" maxSpeed="{CAR_MAX_SPEED_MPS}"/>',
    ]
    flows = [
        (source, target, period)
        for source, targets in periods_s.items()
        for target, period in targets.items()
    ]
    for index, (source, target, _period) in enumerate(flows):
        lines.append(f'    <route id="r{index}" edges="{source} {target}"/>')
    for index, (_source, _target, period) in enumerate(flows):
        lines.append(
            f'    <flow id="f{index}" route="r{index}" type="car" '
            f'begin="0.00" end="{depart_end_s:.2f}" period="{period:.2f}" departLane="free"/>'
        )
    lines.append("</routes>")
    output.write_text("\n".join(lines) + "\n")


def _turning_scenario_yaml(
    scenario_id: str, description_body: str, *, end_s: float, time_to_teleport_s: float
) -> str:
    return (
        f"scenario_id: {scenario_id}\n"
        "scenario_version: 1\n"
        "description: >\n"
        f"{description_body}"
        "network_file: network.net.xml\n"
        "demand_file: demand.rou.xml\n"
        "begin_s: 0.0\n"
        f"end_s: {end_s:.1f}\n"
        "step_length_s: 1.0\n"
        f"time_to_teleport_s: {time_to_teleport_s:.1f}\n"
        "default_seed: 1\n"
    )


TURNING_DESCRIPTION = (
    "  The s0_cross network under an asymmetric turning demand. Every controlled link carries\n"
    "  traffic, and every approach lane serves two movements, so shared-lane queue attribution\n"
    "  and turn-ratio estimation have something to measure. Integration testing only.\n"
    "  Not for research claims.\n"
)

TURNING_SCENARIO_YAML = _turning_scenario_yaml(
    "s0_turning", TURNING_DESCRIPTION, end_s=600.0, time_to_teleport_s=300.0
)

OVERSATURATED_SCENARIO_ROOT = REPO_ROOT / "scenarios" / "s0_turning_oversaturated" / "v1"

# Divides every TURNING_PERIODS_S entry, keeping their ratios -- not one flattened period --
# so the asymmetry that lets a movement-mapping error be caught survives (spec
# docs/specs/2026-08-27-m1b-metrics.md section 10.2 -- flattening destroys the property this
# module's own comment says the demand exists for, that a movement-mapping error cannot hide
# behind symmetry. Note that scaling buys no detection advantage over flattening: both score
# 3 of 16 pairs against section 8's permutation. The reason is the invariant, not the count.
# Measured at this scale over a 180 s
# horizon (task-2 report): 361 departed, 178 still active, 349 never inserted, 13 teleports.
OVERSATURATED_PERIOD_SCALE = 6.0

OVERSATURATED_PERIODS_S: dict[str, dict[str, float]] = {
    source: {target: period / OVERSATURATED_PERIOD_SCALE for target, period in targets.items()}
    for source, targets in TURNING_PERIODS_S.items()
}

# Short enough to keep the test suite fast; equal to the demand's own depart window (below),
# so the run cannot drain before the horizon by construction.
OVERSATURATED_END_S = 180.0

# Below OVERSATURATED_END_S, unlike the 300.0 s inherited default: spec section 10.2 measured
# that 300.0 against a 180 s horizon makes a teleport structurally impossible, leaving every
# teleport metric untested against the code path it exists for.
OVERSATURATED_TIME_TO_TELEPORT_S = 30.0

OVERSATURATED_DESCRIPTION = (
    "  s0_turning under an oversaturated regime: TURNING_PERIODS_S scaled, not flattened, so\n"
    "  the asymmetry that catches a movement-mapping error survives. A parameterised regime of\n"
    "  s0_turning (TC-D01), not a new network; its own scenario id exists only because\n"
    "  ScenarioConfig has no regime dimension yet. Integration testing only. Not for research\n"
    "  claims.\n"
)

OVERSATURATED_SCENARIO_YAML = _turning_scenario_yaml(
    "s0_turning_oversaturated",
    OVERSATURATED_DESCRIPTION,
    end_s=OVERSATURATED_END_S,
    time_to_teleport_s=OVERSATURATED_TIME_TO_TELEPORT_S,
)


def main() -> int:
    for root in (SCENARIO_ROOT, TURNING_SCENARIO_ROOT, OVERSATURATED_SCENARIO_ROOT):
        root.mkdir(parents=True, exist_ok=True)
        build_network(root / "network.net.xml")
    build_demand(SCENARIO_ROOT / "network.net.xml", SCENARIO_ROOT / "demand.rou.xml")
    build_turning_demand(TURNING_SCENARIO_ROOT / "demand.rou.xml")
    (TURNING_SCENARIO_ROOT / "scenario.yaml").write_text(TURNING_SCENARIO_YAML)
    build_turning_demand(
        OVERSATURATED_SCENARIO_ROOT / "demand.rou.xml",
        periods_s=OVERSATURATED_PERIODS_S,
        depart_end_s=OVERSATURATED_END_S,
    )
    (OVERSATURATED_SCENARIO_ROOT / "scenario.yaml").write_text(OVERSATURATED_SCENARIO_YAML)
    print(f"Wrote {SCENARIO_ROOT}, {TURNING_SCENARIO_ROOT} and {OVERSATURATED_SCENARIO_ROOT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
