"""Generates the S0 deterministic single-intersection scenario.

Routes are derived from the generated network rather than hand-written, because
netgenerate owns the edge identifiers. Re-running this script reproduces the committed
files byte for byte, on any machine.
"""

from __future__ import annotations

import functools
import math
import re
import subprocess
import sys
from pathlib import Path

# GOTCHA: importing sumo is what sets SUMO_HOME.
import sumo
import sumolib

REPO_ROOT = Path(__file__).resolve().parents[1]
SCENARIO_ROOT = REPO_ROOT / "scenarios" / "s0_single_intersection" / "v1"

GRID_LENGTH_M = 200.0  # Approach length; long enough to hold a queue without spilling out.
ATTACH_LENGTH_M = 200.0  # Stub length on each of the four approaches.
LANES_PER_DIRECTION = 2  # Minimum that permits a separate turning movement later.

# One vehicle every 6 s per approach = 600 veh/h/approach, comfortably undersaturated for
# a two-lane approach (regime A). S0 exists to be predictable.
HEADWAY_S = 6.0
# Departures stop two minutes before the scenario horizon of 600 s so the network drains
# on its own; S0 should exercise the drain path, not the horizon cut-off.
DEPART_END_S = 480.0

# PROVENANCE: SUMO's own default passenger-car vType (`sumo/src/microsim/MSVehicleType`
# / the vType.xsd defaults) — S0's fleet is intentionally the SUMO default, not a tuned one.
CAR_ACCEL_MPS2 = 2.6
CAR_DECEL_MPS2 = 4.5
CAR_LENGTH_M = 5.0
CAR_MAX_SPEED_MPS = 13.9  # 50 km/h, SUMO's default vType speed limit.


def build_network(output: Path) -> None:
    binary = Path(sumo.SUMO_HOME) / "bin" / "netgenerate"
    # netgenerate records the output path it was given inside the file, so it is invoked
    # from the scenario directory with a relative name; an absolute path would embed the
    # generating machine's filesystem in a committed, publicly published artifact.
    subprocess.run(
        [
            str(binary),
            "--grid",
            "--grid.number=1",
            f"--grid.length={GRID_LENGTH_M}",
            f"--grid.attach-length={ATTACH_LENGTH_M}",
            f"--default.lanenumber={LANES_PER_DIRECTION}",
            "--tls.guess=true",
            "--tls.default-type=static",
            "--no-turnarounds=true",
            "--output-file",
            output.name,
        ],
        cwd=output.parent,
        check=True,
    )
    _strip_generation_timestamp(output)


def _strip_generation_timestamp(network: Path) -> None:
    """Remove the wall-clock stamp netgenerate writes into its header comment.

    A scenario's identity is the sha256 of its files, so the bytes must depend only on the
    generator's inputs. The option list in the header is kept: it is real provenance.
    """
    network.write_text(re.sub(r"generated on [^ ]+ by", "generated by", network.read_text()))


def _unit_direction(edge: sumolib.net.edge.Edge) -> tuple[float, float]:
    (x0, y0), (x1, y1) = edge.getShape()[0], edge.getShape()[-1]
    dx, dy = x1 - x0, y1 - y0
    norm = math.hypot(dx, dy)
    return dx / norm, dy / norm


def _alignment(heading: tuple[float, float], edge: sumolib.net.edge.Edge) -> float:
    dx, dy = _unit_direction(edge)
    return heading[0] * dx + heading[1] * dy


def _approach_pairs(net: sumolib.net.Net) -> list[tuple[str, str]]:
    """Each incoming stub paired with its straight-through outgoing stub.

    The straight-through movement is the outgoing edge whose heading is closest to the
    incoming one, which is the one maximising the dot product of the unit directions.
    """
    junction = next(node for node in net.getNodes() if node.getType() == "traffic_light")
    outgoing = sorted(junction.getOutgoing(), key=lambda edge: edge.getID())
    pairs: list[tuple[str, str]] = []
    for in_edge in sorted(junction.getIncoming(), key=lambda edge: edge.getID()):
        best = max(outgoing, key=functools.partial(_alignment, _unit_direction(in_edge)))
        pairs.append((in_edge.getID(), best.getID()))
    return pairs


def build_demand(network: Path, output: Path) -> None:
    net = sumolib.net.readNet(str(network))
    pairs = _approach_pairs(net)
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<routes>",
        f'    <vType id="car" accel="{CAR_ACCEL_MPS2}" decel="{CAR_DECEL_MPS2}" sigma="0.0" '
        f'length="{CAR_LENGTH_M}" maxSpeed="{CAR_MAX_SPEED_MPS}"/>',
    ]
    for index, (source, target) in enumerate(pairs):
        lines.append(f'    <route id="r{index}" edges="{source} {target}"/>')
    for index, _ in enumerate(pairs):
        lines.append(
            f'    <flow id="f{index}" route="r{index}" type="car" '
            f'begin="0.00" end="{DEPART_END_S:.2f}" period="{HEADWAY_S:.2f}" departLane="free"/>'
        )
    lines.append("</routes>")
    output.write_text("\n".join(lines) + "\n")


def main() -> int:
    SCENARIO_ROOT.mkdir(parents=True, exist_ok=True)
    network = SCENARIO_ROOT / "network.net.xml"
    build_network(network)
    build_demand(network, SCENARIO_ROOT / "demand.rou.xml")
    print(f"Wrote {network} and {SCENARIO_ROOT / 'demand.rou.xml'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
